import express from 'express';
import authenticateJWT from '../middlewares/authMiddleware.js';
import { chatWithAI, generateCourseDescription, refineCourseDescription, saveModuleContents, getModuleContents, generateModuleDraft, generateSingleModule, generateAllModulesDraft } from '../controllers/aiController.js';
const router = express.Router();
router.post('/chat', authenticateJWT, chatWithAI);
router.post('/generate-course-description', authenticateJWT, generateCourseDescription);
router.post('/refine-course-description', authenticateJWT, refineCourseDescription);
router.post('/module-contents', authenticateJWT, saveModuleContents);
router.get('/module-contents', authenticateJWT, getModuleContents);
router.post('/generate-module-draft', authenticateJWT, generateModuleDraft);
router.post('/generate-module', authenticateJWT, generateSingleModule);
router.post('/generate-all-modules-draft', authenticateJWT, generateAllModulesDraft);
export default router;
