import express from 'express';
import multer from 'multer';
import authenticateJWT from '../middlewares/authMiddleware.js';
import { chatWithAI, generateCourseDescription, refineCourseDescription, saveModuleContents, getModuleContents, generateModuleDraft, generateSingleModule, generateAllModulesDraft, generateResearchDossier, generateCourseBlueprint, generateNarration, generateAssessment, generateWorkbook, auditCourse, extractCourseSource, generateBriefField, fixScopeWithAudit, generateModuleTask } from '../controllers/aiController.js';
const router = express.Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 15 * 1024 * 1024 } });
router.post('/chat', authenticateJWT, chatWithAI);
router.post('/generate-course-description', authenticateJWT, generateCourseDescription);
router.post('/refine-course-description', authenticateJWT, refineCourseDescription);
router.post('/module-contents', authenticateJWT, saveModuleContents);
router.get('/module-contents', authenticateJWT, getModuleContents);
router.post('/generate-module-draft', authenticateJWT, generateModuleDraft);
router.post('/generate-module', authenticateJWT, generateSingleModule);
router.post('/generate-all-modules-draft', authenticateJWT, generateAllModulesDraft);
router.post('/generate-research-dossier', authenticateJWT, generateResearchDossier);
router.post('/generate-course-blueprint', authenticateJWT, generateCourseBlueprint);
router.post('/generate-narration', authenticateJWT, generateNarration);
router.post('/generate-assessment', authenticateJWT, generateAssessment);
router.post('/generate-workbook', authenticateJWT, generateWorkbook);
router.post('/audit-course', authenticateJWT, auditCourse);
router.post('/course-sources', authenticateJWT, upload.single('file'), extractCourseSource);
router.post('/generate-brief-field', authenticateJWT, generateBriefField);
router.post('/fix-scope-with-audit', authenticateJWT, fixScopeWithAudit);
router.post('/generate-module-task', authenticateJWT, generateModuleTask);
export default router;
