import express from 'express';
import authenticateJWT from '../middlewares/authMiddleware.js';
import { createCourse, saveCourseData, getUserCourses, deleteCourse, getCourseModules, searchCourses, getUserCourseData } from '../controllers/courseController.js';
const router = express.Router();
router.post('/create-course', authenticateJWT, createCourse);
router.post('/save-course-data', authenticateJWT, saveCourseData);
router.get('/get-user-courses', authenticateJWT, getUserCourses);
router.delete('/delete-course/:courseId', authenticateJWT, deleteCourse);
router.get('/get-course-modules/:courseId', authenticateJWT, getCourseModules);
router.get('/search-courses', authenticateJWT, searchCourses);
router.get('/get-user-course-data', authenticateJWT, getUserCourseData);
router.post('/', authenticateJWT, createCourse);
router.delete('/:courseId', authenticateJWT, deleteCourse);
router.get('/search', authenticateJWT, searchCourses);
router.get('/me', authenticateJWT, getUserCourses);
export default router;
